### ISSUE TITLE
SR-related issues for duneanaobj v03_01_00

### ISSUE THREAD

**Issue by sindhu-ku** [DUNE/duneanaobj#21]
- [x] Replace `TrueParticleID truth` with `std::vector<TrueParticleID> truth` in` SRShower` and `SRTrack` 
- [x] Memory issues with `mc.nu` branch: `(free(): invalid pointer)`. Also noticed for `common.ixn.dlp` when truth matching is performed 
- [ ] Not able to fill reco particle momentum using `caf::SRVector3D()`, currently done this way `p.x = part.momentum[0] `etc., in `ND_CAFMaker`. This however works for start and end positions.
- [x] Fix missing dictionaries for `SRNDTrkAssnBranch`, `SRNDShwAssnBranch`, `vector<vector<vector<unsigned long>>>`

**Comment by chenel** [comment]
>  Replace std::vector<TrueParticleID> truth in SRRecoParticle.h with TrueParticleID truth

Wait.  This was turned into a vector on purpose.  See 73095d2 commit message.  We don't want to undo that.

**Comment by chenel** [comment]
the `free: invalid pointer` stuff seems to have solved itself with this new version?  but I'm unclear whether it will resurface.

**Comment by chenel** [comment]
I didn't try to solve the `p.x` etc. thing here.
