### ISSUE TITLE
Bring into dunesw stack?

### ISSUE THREAD

**Issue by calcuttj** [DUNE/duneanaobj#8]
Should this be brought under the dunesw stack? I noticed that the version got bumped up here but not within duneana. Should the version be bumped up there?

**Comment by cjbackhouse** [comment]
Yeah, potentially? Failing to bump the version in duneana was an oversight. Would having this part of dunesw make that automatic in some way?

**Comment by calcuttj** [comment]
If we include it in the stack, we could have it be part of the rolling release schedule, but then it would gain many more versions than is really necessary. So that's probably not the right way to do it

**Comment by calcuttj** [comment]
Simplest thing is to just put in an issue on duneana to bump up the duneanaobj version when it's updated. That way someone will likely catch it

**Comment by calcuttj** [comment]
@cjbackhouse I'm working on this week's release -- do you want me to update the duneanaobj version?

**Comment by cjbackhouse** [comment]
Yes please
